In [1]:
# Is the pytorch successfully installed?
import torch
import numpy as np
a = torch.rand(3,5)
print(a)
b = torch.device('mps')
print(b)

IOStream.flush timed out


tensor([[0.1138, 0.8173, 0.0841, 0.6530, 0.2767],
        [0.1576, 0.2298, 0.6188, 0.6300, 0.5020],
        [0.3247, 0.7782, 0.9924, 0.0313, 0.8101]])
mps


In [2]:
# Is pytorch calculate on GPU?
torch.cuda.is_available()

False

In [3]:
torch.__version__
torch.device("mps")

device(type='mps')

In [4]:
torch.__version__

'2.1.0.dev20230317'

# Tensor Initialization

## 1.Directly from data

In [5]:
# Tensors can be created directly from data. The data type is automatically inferred.
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

## 2.From a NumPy array

In [6]:
# Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label).
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

## 3.From another tensor:

In [7]:
# The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden（显式覆盖）.
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9997, 0.6730],
        [0.5209, 0.5577]]) 



## 4.With random or constant values:

In [8]:
# shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.
shape = (2, 6,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
empty_tensor = torch.empty(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")
print(f"empty Tensor: \n {empty_tensor}")

Random Tensor: 
 tensor([[0.6214, 0.8485, 0.8936, 0.8008, 0.3649, 0.2769],
        [0.3868, 0.5099, 0.7692, 0.8164, 0.6937, 0.0632]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
empty Tensor: 
 tensor([[7.8675e+34, 4.6894e+27, 1.6217e-19, 7.3471e+28, 2.6383e+23, 2.7376e+20],
        [6.3828e+28, 1.4603e-19, 1.8888e+31, 4.9656e+28, 7.9463e+08, 3.2604e-12]])


## 总结  

总结来说，一般 tensor_A 的初始化的方式有：  
1.直接从已有数据 ex_data 获得：torch.tensor(ex_data)  
2.由numpy向量np_array传得：torch.from_numpy(np_array)  
3.由另一个 tensor_B 传得  

    a.生成与 tensor_B 尺寸一致但内容不同的 tensor_A：torch.xx_like(tensor_B)  
    b.通过设定规则(如"dtype=torch.float") 生成与 tensor_B 在规定处不同的 tensor_A：torch.xx_like(torch_B, dtype=torch.float)   
4.根据已知shape生成  

    a.随机生成：torch.rand(shape)  
    b.全1生成：torch.ones(shape)  
    c.全0生成：torch.zeros(shape)  
    d.未初始化生成：torch.empty(shape)  

# Tensor Attributes
Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [9]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 总结
tensor有三个属性，分别是：  
1.tensor的尺寸：tensor.shape  
2.tensor的数据格式：tensor.dtype  
3.tensor数据的存储位置：tensor.device

#  "Bridge with numpy"
Data in tensor zand numpy share their underlying memory locations, and changing one will change another.

In [10]:
# From tensor to numpy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [11]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [12]:
# From numpy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)
# Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## 总结
Tensor 和 Numpy 的数组可以相互转换，并且两者转换后共享在 CPU 下的内存空间，即改变其中一个的数值，另一个变量也会随之改变。

# Tensor Operations
Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described here(https://pytorch.org/docs/stable/torch.html).
Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Edit > Notebook Settings.

## Tensor with cuda

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

In [ ]:
# 当 CUDA 可用的时候，可用运行下方这段代码，采用 torch.device() 方法来改变 tensors 是否在 GPU 上进行计算操作
if torch.cuda.is_available():
    device = torch.device("cuda")          # 定义一个 CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 显示创建在 GPU 上的一个 tensor
    x = x.to(device)                       # 也可以采用 .to("cuda") 
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # .to() 方法也可以改变数值类型
# 输出结果
# 第一个结果就是在 GPU 上的结果，打印变量的时候会带有 device='cuda:0'，而第二个是在 CPU 上的变量。
# tensor([1.4549], device='cuda:0')
# tensor([1.4549], dtype=torch.float64)

## 1.Standard numpy-like indexing and slicing:
Try out some of the operations from the list. If you’re familiar with the NumPy API, you’ll find the Tensor API a breeze to use.

In [18]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 2.Joining tensors
Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining op that is subtly different from torch.cat.

In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## 3.Multiplying tensors

In [21]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")
# This computes the matrix multiplication between two tensors
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


## 4.In-place operations 
Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.  
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [22]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## 总结
1.对tensor的引索和切片可以按照numpy格式  
2.tensor的拼接：torch.cat()
3.tensor的四则运算：  
    
    a.加减法：直接使用'+'，'-'
    b.乘法：
    
        i.tensor的叉乘：torch.mul(input_tensor,other) other可以是数字/tensor
        ii.tensor的点乘：torch_A * torch_B
        iii.tensor的宽泛矩阵乘积：tensor.matmul(tensor_1,tensor_2)  
4.tensor_A的置换运算（即改变tensor_A本身的值）： 

    a.置换加：tensor_A.add_()
    b.置换乘：tensor_A.mul_()
    c.以此类推，基本上都有置换

### 宽泛矩阵乘积的各种特殊情况

In [23]:
# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2).size()
# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()
# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()
# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

tensor([ 0.1167,  0.6392, -1.2594])